options(scipen = 100)
options(Encoding="UTF-8")

library(httr)
library(jsonlite)
library(tidyverse)
library(gtsummary)
library(gghighlight)
library(png)
library(grid)
library(viridis)
library(ggplot2)
library(showtext)
library(ggrepel)
library(cowplot)
library(ggtext)
library(extrafont)
library(scales)
library(ggridges)
library(janitor)
library(magick)
library(jpeg)
library(zoo)
library(data.table)
library(ggpubr)
library(ggExtra)
library(ggplotify)
